version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/src/UI"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
  - package-ecosystem: "nuget"
    directory: "/src/WebAPI"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
